service: renapp-admin
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  memorySize: 128
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}
custom:
  defaultStage: dev
  profiles:
    dev: renapp-admin
    prod: renapp-admin
functions:
  app:
    handler: dist/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    vpc:
      securityGroupIds:
        - sg-07a4c1dcf87ef7398
      subnetIds:
        - subnet-bfea26f2
        - subnet-6adfa803
        - subnet-e1962a9a
package:
  exclude:
    - src/**
    - .env
  include:
    - dist/**
plugins:
  - serverless-offline
